/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.cientifica;

/**
 *
 * @author Familia
 */

public class CalculadoraCientificaJF extends javax.swing.JFrame {
    
    /**
     * Creates new form teste
     */
    
    //Declaração dos atributos
    private boolean igual,inicio = true, operacao1, operacao2;
    private double cos,sin,tan, memoria = 0, resultado,valor1,valor2;
    private String funcoes,tipoOperacoes;
   
    public CalculadoraCientificaJF() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entrada_principal = new javax.swing.JTextField();
        entrada_secundaria = new javax.swing.JTextField();
        num_1 = new javax.swing.JButton();
        num_2 = new javax.swing.JButton();
        num_3 = new javax.swing.JButton();
        num_4 = new javax.swing.JButton();
        num_5 = new javax.swing.JButton();
        num_6 = new javax.swing.JButton();
        num_7 = new javax.swing.JButton();
        num_8 = new javax.swing.JButton();
        num_9 = new javax.swing.JButton();
        num_0 = new javax.swing.JButton();
        botao_soma = new javax.swing.JButton();
        botao_subtracao = new javax.swing.JButton();
        botao_multiplicacao = new javax.swing.JButton();
        botao_divisao = new javax.swing.JButton();
        botao_seno = new javax.swing.JButton();
        botao_cosseno = new javax.swing.JButton();
        botao_tangente = new javax.swing.JButton();
        botao_logaritmo = new javax.swing.JButton();
        botao_exponencial = new javax.swing.JButton();
        botao_pi = new javax.swing.JButton();
        botao_euler = new javax.swing.JButton();
        botao_AC = new javax.swing.JButton();
        botao_MC = new javax.swing.JButton();
        botao_MR = new javax.swing.JButton();
        botao_Mmenos = new javax.swing.JButton();
        botao_Mmais = new javax.swing.JButton();
        botao_igual = new javax.swing.JButton();
        botao_ponto = new javax.swing.JButton();
        radio_rad = new javax.swing.JRadioButton();
        radio_sexages = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entrada_principal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        entrada_principal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entrada_principal.setText("0");
        entrada_principal.setBorder(null);
        entrada_principal.setFocusable(false);
        entrada_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_principalActionPerformed(evt);
            }
        });

        entrada_secundaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entrada_secundaria.setBorder(null);
        entrada_secundaria.setFocusable(false);
        entrada_secundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_secundariaActionPerformed(evt);
            }
        });

        num_1.setText("1");
        num_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_1ActionPerformed(evt);
            }
        });

        num_2.setText("2");
        num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_2ActionPerformed(evt);
            }
        });

        num_3.setText("3");
        num_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_3ActionPerformed(evt);
            }
        });

        num_4.setText("4");
        num_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_4ActionPerformed(evt);
            }
        });

        num_5.setText("5");
        num_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_5ActionPerformed(evt);
            }
        });

        num_6.setText("6");
        num_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_6ActionPerformed(evt);
            }
        });

        num_7.setText("7");
        num_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_7ActionPerformed(evt);
            }
        });

        num_8.setText("8");
        num_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_8ActionPerformed(evt);
            }
        });

        num_9.setText("9");
        num_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_9ActionPerformed(evt);
            }
        });

        num_0.setText("0");
        num_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_0ActionPerformed(evt);
            }
        });

        botao_soma.setText("+");
        botao_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_somaActionPerformed(evt);
            }
        });

        botao_subtracao.setText("-");
        botao_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_subtracaoActionPerformed(evt);
            }
        });

        botao_multiplicacao.setText("*");
        botao_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_multiplicacaoActionPerformed(evt);
            }
        });

        botao_divisao.setText("/");
        botao_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_divisaoActionPerformed(evt);
            }
        });

        botao_seno.setText("sen");
        botao_seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_senoActionPerformed(evt);
            }
        });

        botao_cosseno.setText("cos");
        botao_cosseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cossenoActionPerformed(evt);
            }
        });

        botao_tangente.setText("tan");
        botao_tangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_tangenteActionPerformed(evt);
            }
        });

        botao_logaritmo.setText("log");
        botao_logaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_logaritmoActionPerformed(evt);
            }
        });

        botao_exponencial.setText("EXP");
        botao_exponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_exponencialActionPerformed(evt);
            }
        });

        botao_pi.setText("PI");
        botao_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_piActionPerformed(evt);
            }
        });

        botao_euler.setText("E");
        botao_euler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_eulerActionPerformed(evt);
            }
        });

        botao_AC.setText("AC");
        botao_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ACActionPerformed(evt);
            }
        });

        botao_MC.setText("MC");
        botao_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_MCActionPerformed(evt);
            }
        });

        botao_MR.setText("MR");
        botao_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_MRActionPerformed(evt);
            }
        });

        botao_Mmenos.setText("M-");
        botao_Mmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_MmenosActionPerformed(evt);
            }
        });

        botao_Mmais.setText("M+");
        botao_Mmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_MmaisActionPerformed(evt);
            }
        });

        botao_igual.setText("=");
        botao_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_igualActionPerformed(evt);
            }
        });

        botao_ponto.setText(".");
        botao_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pontoActionPerformed(evt);
            }
        });

        radio_rad.setText("Radianos");

        radio_sexages.setSelected(true);
        radio_sexages.setText("Sexagesimal");
        radio_sexages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_sexagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entrada_principal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botao_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao_tangente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_logaritmo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botao_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao_seno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_cosseno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num_4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num_6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(num_0, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botao_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botao_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(num_3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botao_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num_7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(num_9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botao_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botao_AC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botao_exponencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(entrada_secundaria)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botao_Mmais, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(radio_sexages)
                        .addGap(18, 18, 18)
                        .addComponent(radio_rad)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(entrada_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_MC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_MR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Mmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Mmais, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_rad)
                    .addComponent(radio_sexages))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_AC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_seno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_exponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_cosseno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botao_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao_logaritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botao_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_euler, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrada_secundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_secundariaActionPerformed
     
    }//GEN-LAST:event_entrada_secundariaActionPerformed

    //Botão de subtração
    private void botao_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_subtracaoActionPerformed
        igual = true;
        inicio = true;
           
        //Condição para a variável "operacao1"
        if (operacao1 = true) {
            valor1 = Double.parseDouble(entrada_principal.getText());
            entrada_secundaria.setText("");
            entrada_secundaria.setText(entrada_principal.getText()+ "-");
            operacao1 = false;
        }else{
            //Condição para a variável "operacao2"
            if (operacao2 = true) {
                valor2 = Double.parseDouble(entrada_principal.getText());
                entrada_secundaria.setText(entrada_principal.getText()+ "-");
                operacao2 = false;
            }else{
                entrada_secundaria.setText(entrada_principal.getText()+ "-");
                Operacoes(resultado,valor2);
            }
        }
        //Tipo da operação
        tipoOperacoes = "-";
    }//GEN-LAST:event_botao_subtracaoActionPerformed

    //Botão de Multiplicação
    private void botao_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_multiplicacaoActionPerformed
        igual = true;
        inicio = true;
           
        //Condição para a variável "operacao1"
        if (operacao1 = true) {
            valor1 = Double.parseDouble(entrada_principal.getText());
            entrada_secundaria.setText("");
            entrada_secundaria.setText(entrada_principal.getText()+ "*");
            operacao1 = false;
        }else{
            //Condição para a variável "operacao2"
            if (operacao2 = true) {
                valor2 = Double.parseDouble(entrada_principal.getText());
                entrada_secundaria.setText(entrada_principal.getText()+ "*");
                operacao2 = false;
            }else{
                entrada_secundaria.setText(entrada_principal.getText()+ "*");
                Operacoes(resultado,valor2);
            }
        }
        //Tipo de operação
        tipoOperacoes = "*";
    }//GEN-LAST:event_botao_multiplicacaoActionPerformed

    //Botão de divisão
    private void botao_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_divisaoActionPerformed
        igual = true;
        inicio = true;
           
        //Condição para a variável "operacao1"
        if (operacao1 = true) {
            valor1 = Double.parseDouble(entrada_principal.getText());
            entrada_secundaria.setText("");
            entrada_secundaria.setText(entrada_principal.getText()+ "/");
            operacao1 = false;
        }else{
            //Condição para a variável "operacao2"
            if (operacao2 = true) {
                valor2 = Double.parseDouble(entrada_principal.getText());
                entrada_secundaria.setText(entrada_principal.getText()+ "/");
                operacao2 = false;
            }else{
                entrada_secundaria.setText(entrada_principal.getText()+ "/");
                Operacoes(resultado,valor2);
            }
        }
        //Tipo de operação
        tipoOperacoes = "/";
    }//GEN-LAST:event_botao_divisaoActionPerformed

    //Método trigonometria
    public void Trigonometria() {
        //Condição que valida se o radio "sexagesimal" está selecionado
        if (radio_sexages.isSelected()) {
            //Switch da variável "funcoes"
            switch(funcoes){
                //Seno
                case "sen":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" sen( " +valor1+" )");
                    sin = Math.sin(Math.PI*(valor1)/180);
                    entrada_principal.setText(sin+" ");
                    break;
                //Cosseno
                case "cos":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" cos( " +valor1+" )");
                    cos = Math.cos(Math.PI*(valor1)/180);
                    entrada_principal.setText(cos+" ");
                    break;
                //Tangente
                case "tan":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" tan( " +valor1+" )");
                    tan = Math.tan(Math.PI*(valor1)/180);
                    entrada_principal.setText(tan+" ");
                    break;
            }
        }else{
            //Condição que valida se o radio "radianos" está selecionado
        if (radio_rad.isSelected()) {
            //Switch da variável "funcoes"
            switch(funcoes){
                //Seno
                case "sen":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" senr( " +valor1+" )");
                    sin = Math.sin(valor1);
                    entrada_principal.setText(sin+" ");
                    break;
                //Cosseno
                case "cos":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" cosr( " +valor1+" )");
                    cos = Math.cos(valor1);
                    entrada_principal.setText(cos+" ");
                    break;
                //Tangente
                case "tan":
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    entrada_secundaria.setText(" tanr( " +valor1+" )");
                    tan = Math.tan(valor1);
                    entrada_principal.setText(tan+" ");
                    break;
            }
        }
        }
    }
    private void botao_senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_senoActionPerformed
        funcoes = "sen";
        Trigonometria();
    }//GEN-LAST:event_botao_senoActionPerformed

    private void botao_cossenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cossenoActionPerformed
        funcoes = "cos";
        Trigonometria();
    }//GEN-LAST:event_botao_cossenoActionPerformed

    private void botao_tangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_tangenteActionPerformed
        funcoes = "tan";
        Trigonometria();
    }//GEN-LAST:event_botao_tangenteActionPerformed

    //Botão de Logaritmo
    private void botao_logaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_logaritmoActionPerformed
        valor1 = Double.parseDouble(entrada_principal.getText());
        entrada_secundaria.setText("log( " + valor1 + ") ");
        entrada_principal.setText(Math.log10(valor1) + " ");
    }//GEN-LAST:event_botao_logaritmoActionPerformed

    //Botão de Exponencial
    private void botao_exponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_exponencialActionPerformed
        valor1 = Double.parseDouble(entrada_principal.getText());
        entrada_secundaria.setText("exp( " + valor1 + ") ");
        entrada_principal.setText(Math.exp(valor1) + " ");
    }//GEN-LAST:event_botao_exponencialActionPerformed

    //Botão que devolve o valor de Pi
    private void botao_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_piActionPerformed
        entrada_secundaria.setText("PI ");
        entrada_principal.setText(Math.PI +" ");
    }//GEN-LAST:event_botao_piActionPerformed

    //Botão que devolve o valor de Euler
    private void botao_eulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_eulerActionPerformed
        entrada_secundaria.setText("E ");
        entrada_principal.setText(Math.E +" ");
        
    }//GEN-LAST:event_botao_eulerActionPerformed

    //Botão AC
    private void botao_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ACActionPerformed
        entrada_principal.setText("0");
        entrada_secundaria.setText("");
        inicio = true;
        funcoes = "";
        operacao1 = true;
        operacao2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
    }//GEN-LAST:event_botao_ACActionPerformed

    //Botao MC
    private void botao_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_MCActionPerformed
        memoria = 0;
        
    }//GEN-LAST:event_botao_MCActionPerformed

    //Botão MR
    private void botao_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_MRActionPerformed
        entrada_principal.setText(memoria + " ");
    }//GEN-LAST:event_botao_MRActionPerformed

    //Botão M-
    private void botao_MmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_MmenosActionPerformed
        memoria = memoria - Double.parseDouble(entrada_principal.getText());
        
    }//GEN-LAST:event_botao_MmenosActionPerformed

    //Botão M+
    private void botao_MmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_MmaisActionPerformed
        memoria = memoria + Double.parseDouble(entrada_principal.getText());
        
    }//GEN-LAST:event_botao_MmaisActionPerformed

    //Método com as operações de soma, subtração, multiplicação e divisão
    private void Operacoes(double valor1, double valor2) {
        //Switch da variável "tipoOperacoes"
        switch(tipoOperacoes){
            //Case para a função de soma
            case "+":
                resultado = valor1 + valor2;
                entrada_principal.setText(resultado + "");
                valor1 = Double.parseDouble(entrada_principal.getText());
                break;
            //Case para a função de subtração
            case "-":
                resultado = valor1 - valor2;
                entrada_principal.setText(resultado + "");
                valor1 = Double.parseDouble(entrada_principal.getText());
                break;
            //Case para a função de multiplicação
            case "*":
                resultado = valor1 * valor2;
                entrada_principal.setText(resultado + "");
                valor1 = Double.parseDouble(entrada_principal.getText());
                break;
            //Case para a função de divisão
            case "/":
                //Controle de erros
                //Se a operação for um número qualquer dividido por 0, aparece erro na tela
                if (valor2 == 0) {
                    entrada_principal.setText("Erro ");
                    break;
                }else{
                   resultado = valor1 / valor2;
                    entrada_principal.setText(resultado + "");
                    valor1 = Double.parseDouble(entrada_principal.getText());
                    break; 
                }
                
        }
    }
    
    //Botão de igualdade
    private void botao_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_igualActionPerformed
        inicio = true;
        operacao1 = true;
        if(igual = true) {
            if(tipoOperacoes == null) {
                
            }else{
                valor2 = Double.parseDouble(entrada_principal.getText());
                entrada_secundaria.setText(entrada_secundaria.getText()+entrada_principal.getText());
                Operacoes(valor1,valor2);
                igual = false;
            }
        }else{
            entrada_secundaria.setText("");
            Operacoes(valor1,valor2);
        }
    }//GEN-LAST:event_botao_igualActionPerformed

    //Botões Numéricos
    private void num_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_0ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("0");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"0");
        }
    }//GEN-LAST:event_num_0ActionPerformed

    private void num_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_1ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("1");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"1");
        }
    }//GEN-LAST:event_num_1ActionPerformed

    private void num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_2ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("2");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"2");
        }
    }//GEN-LAST:event_num_2ActionPerformed

    private void num_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_3ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("3");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"3");
        }
    }//GEN-LAST:event_num_3ActionPerformed

    private void num_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_4ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("4");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"4");
        }
    }//GEN-LAST:event_num_4ActionPerformed

    private void num_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_5ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("5");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"5");
        }
    }//GEN-LAST:event_num_5ActionPerformed

    private void num_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_6ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("6");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"6");
        }
    }//GEN-LAST:event_num_6ActionPerformed

    private void num_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_7ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("7");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"7");
        }
    }//GEN-LAST:event_num_7ActionPerformed

    private void num_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_8ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("8");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"8");
        }
    }//GEN-LAST:event_num_8ActionPerformed

    private void num_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_9ActionPerformed
        //Condição para a variável inicio
        if (inicio == true) {
            entrada_principal.setText("");
            entrada_principal.setText("9");
            inicio = false;
        }else{
            entrada_principal.setText(entrada_principal.getText()+"9");
        }
    }//GEN-LAST:event_num_9ActionPerformed

    //Botão de ponto decimal
    private void botao_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pontoActionPerformed
        if (entrada_principal.getText().contains(".")) {
            
        }else{
            entrada_principal.setText(entrada_principal.getText()+".");
            inicio = false;
        }
    }//GEN-LAST:event_botao_pontoActionPerformed

    private void entrada_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_principalActionPerformed
        
    }//GEN-LAST:event_entrada_principalActionPerformed
   
    //Botão de soma
    private void botao_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_somaActionPerformed
        igual = true;
        inicio = true;
           
        //Condição para a variável "operacao1"
        if (operacao1 = true) {
            valor1 = Double.parseDouble(entrada_principal.getText());
            entrada_secundaria.setText("");
            entrada_secundaria.setText(entrada_principal.getText()+ "+");
            operacao1 = false;
        }else{
            //Condição para a variável "operacao2"
            if (operacao2 = true) {
                valor2 = Double.parseDouble(entrada_principal.getText());
                entrada_secundaria.setText(entrada_principal.getText()+ "+");
                operacao2 = false;
            }else{
                entrada_secundaria.setText(entrada_principal.getText()+ "+");
                Operacoes(resultado,valor2);
            }
        }
        //Tipo da operação
        tipoOperacoes = "+";
    }//GEN-LAST:event_botao_somaActionPerformed

    private void radio_sexagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_sexagesActionPerformed
       
    }//GEN-LAST:event_radio_sexagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCientificaJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraCientificaJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_AC;
    private javax.swing.JButton botao_MC;
    private javax.swing.JButton botao_MR;
    private javax.swing.JButton botao_Mmais;
    private javax.swing.JButton botao_Mmenos;
    private javax.swing.JButton botao_cosseno;
    private javax.swing.JButton botao_divisao;
    private javax.swing.JButton botao_euler;
    private javax.swing.JButton botao_exponencial;
    private javax.swing.JButton botao_igual;
    private javax.swing.JButton botao_logaritmo;
    private javax.swing.JButton botao_multiplicacao;
    private javax.swing.JButton botao_pi;
    private javax.swing.JButton botao_ponto;
    private javax.swing.JButton botao_seno;
    private javax.swing.JButton botao_soma;
    private javax.swing.JButton botao_subtracao;
    private javax.swing.JButton botao_tangente;
    private javax.swing.JTextField entrada_principal;
    private javax.swing.JTextField entrada_secundaria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton num_0;
    private javax.swing.JButton num_1;
    private javax.swing.JButton num_2;
    private javax.swing.JButton num_3;
    private javax.swing.JButton num_4;
    private javax.swing.JButton num_5;
    private javax.swing.JButton num_6;
    private javax.swing.JButton num_7;
    private javax.swing.JButton num_8;
    private javax.swing.JButton num_9;
    private javax.swing.JRadioButton radio_rad;
    private javax.swing.JRadioButton radio_sexages;
    // End of variables declaration//GEN-END:variables
}
